### ISSUE TITLE
Setup the project

### ISSUE THREAD

**Issue by JoshAntBrown** [JoshAntBrown/OctoTask#2]
- [x] Setup deployment pipeline JoshAntBrown/OctoTask#3
- [x] Add validation checks JoshAntBrown/OctoTask#4
- [ ] Add test framework JoshAntBrown/OctoTask#7
